-- MySQL Script generated by MySQL Workbench
-- Wed Mar 31 11:06:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema photel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema photel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `photel` DEFAULT CHARACTER SET latin1 ;
USE `photel` ;

-- -----------------------------------------------------
-- Table `photel`.`bedrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`bedrooms` (
  `id_bedrooms` INT(11) NOT NULL,
  `number` INT(3) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `floor` INT(1) NULL DEFAULT NULL,
  `extension_phone` INT(11) NULL DEFAULT NULL,
  `capacity` INT(2) NOT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `type` TINYINT(1) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_bedrooms`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`state` (
  `id_State` INT(11) NOT NULL AUTO_INCREMENT,
  `abbreviation` VARCHAR(2) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_State`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`city` (
  `id_City` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `state_id_State` INT(11) NOT NULL,
  PRIMARY KEY (`id_City`, `state_id_State`),
  INDEX `fk_city_state1_idx` (`state_id_State` ASC),
  CONSTRAINT `fk_city_state1`
    FOREIGN KEY (`state_id_State`)
    REFERENCES `photel`.`state` (`id_State`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`district` (
  `id_District` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `city_id_City` INT(11) NOT NULL,
  PRIMARY KEY (`id_District`, `city_id_City`),
  INDEX `fk_district_city_idx` (`city_id_City` ASC),
  CONSTRAINT `fk_district_city`
    FOREIGN KEY (`city_id_City`)
    REFERENCES `photel`.`city` (`id_City`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`profession` (
  `id_Profession` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Field` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Profession`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`employees` (
  `id_employees` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `Number` INT(11) NOT NULL,
  `Complement` VARCHAR(45) NULL DEFAULT NULL,
  `district` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL DEFAULT '',
  `profession_id_Profession` INT(11) NOT NULL,
  PRIMARY KEY (`id_employees`, `profession_id_Profession`),
  INDEX `fk_employees_profession1_idx` (`profession_id_Profession` ASC) ,
  CONSTRAINT `fk_employees_profession1`
    FOREIGN KEY (`profession_id_Profession`)
    REFERENCES `photel`.`profession` (`id_Profession`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`guest` (
  `id_Guest` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(80) NOT NULL,
  `Cpf` VARCHAR(45) NULL DEFAULT NULL,
  `RG` VARCHAR(45) NULL DEFAULT NULL,
  `Street` VARCHAR(100) NULL DEFAULT NULL,
  `Number` VARCHAR(45) NULL DEFAULT NULL,
  `Complement` VARCHAR(45) NULL DEFAULT NULL,
  `District` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(45) NULL DEFAULT NULL,
  `State` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Guest`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`permission_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`permission_groups` (
  `id_permission_groups` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_permission_groups`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`permission_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`permission_items` (
  `id_permission_items` INT(11) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `type` INT(1) NOT NULL,
  PRIMARY KEY (`id_permission_items`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`permission_links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`permission_links` (
  `id_permission_links` INT(11) NOT NULL,
  `id_permission_groups` INT(11) NOT NULL,
  `id_permission_items` INT(11) NOT NULL,
  PRIMARY KEY (`id_permission_links`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`products` (
  `id_products` INT(10) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NOT NULL,
  `price` FLOAT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_products`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`services` (
  `id_services` INT(10) NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `price` FLOAT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_services`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`street`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`street` (
  `id_Street` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Postal_code` INT NOT NULL,
  `district_id_District1` INT(11) NOT NULL,
  PRIMARY KEY (`id_Street`, `district_id_District1`),
  INDEX `fk_street_district2_idx` (`district_id_District1` ASC) ,
  CONSTRAINT `fk_street_district2`
    FOREIGN KEY (`district_id_District1`)
    REFERENCES `photel`.`district` (`id_District`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `photel`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photel`.`users` (
  `id_users` INT(11) UNSIGNED NOT NULL,
  `password` VARCHAR(32) NOT NULL DEFAULT '',
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `admin` TINYINT(1) NOT NULL DEFAULT '0',
  `token` VARCHAR(32) NULL DEFAULT NULL,
  `employees_id_employees` INT(11) NOT NULL,
  `permission_items_id_permission_items` INT(11) NOT NULL,
  `permission_links_id_permission_links` INT(11) NOT NULL,
  `permission_groups_id_permission_groups` INT(11) NOT NULL,
  PRIMARY KEY (`id_users`, `employees_id_employees`, `permission_items_id_permission_items`, `permission_links_id_permission_links`, `permission_groups_id_permission_groups`),
  INDEX `fk_users_employees1_idx` (`employees_id_employees` ASC) ,
  INDEX `fk_users_permission_items1_idx` (`permission_items_id_permission_items` ASC) ,
  INDEX `fk_users_permission_links1_idx` (`permission_links_id_permission_links` ASC) ,
  INDEX `fk_users_permission_groups1_idx` (`permission_groups_id_permission_groups` ASC) ,
  CONSTRAINT `fk_users_employees1`
    FOREIGN KEY (`employees_id_employees`)
    REFERENCES `photel`.`employees` (`id_employees`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_permission_items1`
    FOREIGN KEY (`permission_items_id_permission_items`)
    REFERENCES `photel`.`permission_items` (`id_permission_items`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_permission_links1`
    FOREIGN KEY (`permission_links_id_permission_links`)
    REFERENCES `photel`.`permission_links` (`id_permission_links`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_permission_groups1`
    FOREIGN KEY (`permission_groups_id_permission_groups`)
    REFERENCES `photel`.`permission_groups` (`id_permission_groups`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
